# Generated by Django 5.1.6 on 2025-02-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitterGourd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'bitter_gourd',
            },
        ),
        migrations.CreateModel(
            name='Brinjals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'brinjals',
            },
        ),
        migrations.CreateModel(
            name='LadyFingerOkra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'ladys_finger_okra',
            },
        ),
        migrations.CreateModel(
            name='LongBeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'long_beans',
            },
        ),
        migrations.CreateModel(
            name='Papaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'papaya',
            },
        ),
        migrations.CreateModel(
            name='Pineapple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'pineapple',
            },
        ),
        migrations.CreateModel(
            name='SnakeGourd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'snake_gourd',
            },
        ),
    ]
