<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-02-27 07:35
=======
# Generated by Django 5.1.6 on 2025-02-23 13:00
>>>>>>> 8e8e5193ef92756218085eb45c6712be1ce57eb2

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('temp', models.FloatField()),
                ('weather', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('temp', models.FloatField()),
                ('wind', models.FloatField()),
                ('humidity', models.FloatField()),
                ('weather', models.CharField(max_length=50)),
            ],
        ),
    ]
